before_script:
  - npm_register ${NPM_TOKEN}

stages:
  - build
  - test
  - publish

deps build:
  stage: build
  script:
    - npm install -q
    - npm run clean
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - build/
    expire_in: 1 week
  tags:
    - lambda-nodejs

lint:
  stage: test
  script:
    - npm run lint
  tags:
    - lambda-nodejs

mocha:
  stage: test
  script:
    - npm test
  tags:
    - lambda-nodejs

npm:
  stage: publish
  script:
    - npm_register ${NPM_TOKEN}
    - npm run build
    - npm publish .
  only:
    - tags@abilio.henrique/serverless-build-substitute-plugin
  tags:
    - lambda-nodejs
